### ISSUE TITLE
redirects to habitfit.herokuapp.com

### ISSUE THREAD

**Issue by NoisyText** [Lamikins/HabitiFit#4]
I tried this on your heroku sever and wanted to try it out on m server. It seems to load correctly until after I try and authenticate with fitbit. After signing into fitbit and giving permission to access my data the browser goes to habitfit.herokuapp.com instead of back to my server christonwalker.com/habitica/fitbit . 
 * I've searched the code couldn't find any links to heroku with no luck. 
 * I've cleared my cache and cookies, didn't seem to make a difference.
 * I've removed the app from my fitbit account retried the problem

Any ideas what's going on or how I can correct the problem?

**Comment by Lamikins** [comment]
Hi NoisyText,

This is because you need to register your own app with fitbit (dev.fitbit.com) before you can run it on your own site.  It will give you a client id, which you can use in place of the current client id in index.php (the 'a' tag with text "Authenticate with Fitbit").  After fitbit authenticates an account, they will redirect the user to your site's url with a hash, which the application then uses to retrieve user data.

Hope this helps.

**Comment by NoisyText** [comment]
Hey, thanks! I'll check into fitbit's dev community. Still pretty new at setting up and running servers etc.
